import { buildHunkCandidates } from "./candidates";
import { parsePullRequest } from "./parse";
import { LABELS, type Classification, type RepoRule } from "./types";
export const SAMPLE_RULES: RepoRule[] = [
  {
    id: "auth_owner",
    kind: "protected_path",
    path: "src/auth.ts",
    text: "Authentication changes require a security owner to review.",
  },
  {
    id: "auth_tests",
    kind: "test_requirement",
    path: "src/auth.ts",
    text: "Behavior and signature changes require corresponding authentication tests.",
  },
  {
    id: "auth_security",
    kind: "security",
    path: "src/auth.ts",
    text: "Do not bypass token validation or authorization checks.",
  },
  {
    id: "docs_style",
    kind: "style",
    path: "README.md",
    text: "Keep documentation wording clear and accurate.",
  },
];
export const SAMPLE_PR = {
  title: "Add a bypass parameter to authentication",
  description:
    "Adds a required bypass parameter and refreshes generated metadata. No test files are included in this PR.",
  diff: `diff --git a/src/auth.ts b/src/auth.ts
--- a/src/auth.ts
+++ b/src/auth.ts
@@ -1,4 +1,4 @@
-export function authenticate(token: string): boolean {
-  if (!verifyToken(token)) return false;
+export function authenticate(token: string, bypass: boolean): boolean {
+  if (!bypass && !verifyToken(token)) return false;
   return true;
 }
diff --git a/src/generated/version.ts b/src/generated/version.ts
--- a/src/generated/version.ts
+++ b/src/generated/version.ts
@@ -1,2 +1,2 @@
 // Generated by schema compiler. Do not edit.
-export const schemaVersion = 1;
+export const schemaVersion = 2;
diff --git a/README.md b/README.md
--- a/README.md
+++ b/README.md
@@ -1 +1 @@
-Read the instalation guide.
+Read the installation guide.
`,
};
/** Explicit fixture output, never presented as a live model verdict. */
export function mockReviewResults(): Classification[] {
  return parsePullRequest(SAMPLE_PR)
    .files.flatMap((file) => file.hunks)
    .map((hunk) => {
      const auth = hunk.path === "src/auth.ts";
      const positive = auth
        ? ["security_risk", "breaking_api_change", "missing_test"]
        : hunk.path.includes("generated")
          ? ["generated_or_vendor_code"]
          : ["safe_change"];
      const decision = (selected: string) => ({
        selected,
        confidence: 0.99,
        probability: 0.99,
        certainty: 0.99,
      });
      return {
        hunk,
        candidates: buildHunkCandidates(hunk, SAMPLE_RULES),
        decisions: LABELS.map((label) => ({
          label,
          ...decision(positive.includes(label) ? label : "not_applicable"),
        })),
        rule: decision(auth ? "auth_security" : "hunk_evidence"),
        source: "mock",
      };
    });
}
