import { ArrowUpRight } from "lucide-react";
const files: [string, string][] = [
  [
    "lib/getElementTable.ts",
    "one atomic DOM snapshot → indexed element table, node identities, freshness guards",
  ],
  [
    "lib/actions.ts",
    "the fixed operation set, the action space, the executor, and the wait strategy",
  ],
  [
    "lib/callJev.ts",
    "one TypeSafe request: operation + every compatible target head",
  ],
  [
    "lib/textHelper.ts",
    "text only for TYPE_TEXT; output must parse as a small JSON object",
  ],
  [
    "lib/validateTarget.ts",
    "freshness, current geometry, and click occlusion before anything executes",
  ],
  [
    "lib/agentLoop.ts",
    "observe → decide → validate → execute → settle, with escalations and budgets",
  ],
  ["lib/logStep.ts", "per-cycle records: table, choice, confidence, outcome"],
  [
    "lib/flightSandbox.ts",
    "the demo task: a synthetic flight site plus its independent verifier",
  ],
];
/** The write-up that accompanies the runnable demo. */
export function BrowserAgentGuide() {
  return (
    <article className="panel agent-guide" aria-label="About this example">
      <section id="intro">
        <h2>A browser agent that chooses instead of writes</h2>
        <p>
          This example ports the loop from{" "}
          <a
            href="https://github.com/browser-use/jev-ultrafast"
            target="_blank"
            rel="noreferrer"
          >
            browser-use/jev-ultrafast
          </a>{" "}
          to the playground. Give it one goal. Every cycle, the page is read
          once into an indexed element table, Jev picks an operation and an
          element, and the executor acts on the observed node. A small LLM is
          called only when the operation is <code>TYPE_TEXT</code>. No
          screenshots feed the policy: Jev consumes structured state, not
          pixels. The reference run searched Zürich → London on a real flights
          site in 7.1 seconds, one-way, with real text generation and loading
          waits. Nothing here is fine-tuned.
        </p>
      </section>
      <section id="why-this-pattern">
        <h2>Why this pattern</h2>
        <ul>
          <li>
            <strong>Closed choices are what Jev is good at.</strong> The element
            table turns a web page into a numbered list, and the operation set
            is fixed. The model never generates selectors, coordinates, or code.
          </li>
          <li>
            <strong>One round trip per decision.</strong> Asking for the
            operation, then the target, doubled the calls and was where an
            earlier prototype degraded. Speculative fan-out requests{" "}
            <code>operation</code>, <code>click_target</code>,{" "}
            <code>type_text_target</code> and <code>select_target</code>{" "}
            together; only the head that matches the chosen operation executes.
          </li>
          <li>
            <strong>Text is a separate, rare job.</strong> A city name or a date
            is generated by a small LLM from the goal and field context, and
            only after Jev chose to type. Its output must parse as{" "}
            <code>{'{"text": "…"}'}</code> before anything is typed.
          </li>
          <li>
            <strong>The page is the truth.</strong> Decisions refer to an
            observed snapshot. Before executing, the loop rechecks document
            freshness, resolves current geometry, and rejects covered or stale
            targets. DONE is checked by an independent verifier that reads the
            resulting page.
          </li>
        </ul>
      </section>
      <section id="the-action-space">
        <h2>The action space</h2>
        <p>
          Every observation produces a new table. One node gets one index, even
          when it supports both clicking and typing:
        </p>
        <pre>{`[1] combobox  Trip type       · Round trip
[2] combobox  Where from?     · empty
[3] combobox  Where to?       · empty
[4] textbox   Departure date  · empty
[5] button    Search flights  · empty`}</pre>
        <p>
          The operations are <code>CLICK</code>, <code>TYPE_TEXT</code>,{" "}
          <code>SELECT</code>, <code>SCROLL_UP</code>, <code>SCROLL_DOWN</code>,{" "}
          <code>WAIT</code>, <code>DONE</code> and <code>BLOCKED</code>. Only
          supported operations and targets are offered: a button never appears
          in <code>type_text_target</code>, and a native dropdown offers its
          options as <code>element:option</code> indexes that the code owns.
        </p>
        <pre>{`                      one TypeSafe request
                     ┌───────────────────────────┐
page → element table → operation                 │
                     │ click_target              │
                     │ type_text_target          │
                     │ select_target, if present │
                     └─────────────┬─────────────┘
                         use the matching target
                                   │
                    CLICK [5] ─────┤──→ sandbox DOM
                TYPE_TEXT [2] ─────┘
                          ↓
                   small LLM → text → sandbox DOM`}</pre>
      </section>
      <section id="implementation">
        <h2>Implementation steps</h2>
        <ol className="agent-steps">
          <li>
            <strong>Perceive once.</strong> <code>getElementTable</code> walks
            the document in one pass: common HTML and ARIA controls, their
            accessible names, current values, checked and expanded state, plus
            the visible text. A WeakMap gives each real node a numeric identity,
            and the snapshot records a semantic marker and per-target guards.
          </li>
          <li>
            <strong>Build the action space.</strong>{" "}
            <code>buildActionSpace</code> groups candidates by operation.
            Editable fields get <code>TYPE_TEXT</code> and a <code>CLICK</code>{" "}
            that opens them; native selects get one <code>SELECT</code>{" "}
            candidate per unselected option; scroll and wait controls appear
            only when they apply.
          </li>
          <li>
            <strong>Ask once.</strong> <code>buildDecisionPayload</code> sends
            the table, the page text and the last ten actions as state, with the
            operation question and one target head per available operation.{" "}
            <code>resolveDecision</code> validates the answer and consumes only
            the matching head. A head with a single candidate is resolved
            locally.
          </li>
          <li>
            <strong>Generate text only when needed.</strong> For{" "}
            <code>TYPE_TEXT</code>, <code>requestFieldText</code> sends the
            goal, the field, the page text and recent actions to the server text
            helper. Its reply must parse as a one-key JSON object. Without a
            text-model key, the lab lets Jev pick a span of the goal instead,
            and labels that clearly.
          </li>
          <li>
            <strong>Validate before acting.</strong> <code>isFresh</code>{" "}
            compares the form and viewport key plus the target's guard for
            clicks, and the full marker for everything else.{" "}
            <code>resolveTarget</code> rereads geometry and hit-tests the centre
            point; a covered control is rejected with the name of what covers
            it, and the rejection goes into the next state as recent history.
          </li>
          <li>
            <strong>Execute, log, then settle.</strong> Execution is recorded
            before the next observation. Typing into a combobox waits for
            visible suggestions, capped at 200 ms; other interactions get two
            animation frames or 50 ms. An explicit <code>WAIT</code> is 100 ms.
          </li>
          <li>
            <strong>Verify DONE independently.</strong>{" "}
            <code>verifyFlightSearch</code> reads the sandbox DOM for the trip
            type, resolved airports, ISO date, passengers, cabin, visible
            matching results and the absence of a selection. A rejected DONE is
            logged, fed back, and after three rejections the run fails instead
            of pretending. A <code>BLOCKED</code> choice also checks for
            completion, then gets one retry from a fresh observation with the
            unmet checks in its history.
          </li>
          <li>
            <strong>Stop honestly.</strong> Budgets cover 40 actions and 80
            decisions. Three consecutive actions that change nothing, four
            consecutive rejections, two consecutive fresh <code>BLOCKED</code>{" "}
            choices, or two consecutive model failures end the run with a reason
            in the log.
          </li>
        </ol>
        <table className="agent-files">
          <tbody>
            {files.map(([file, job]) => (
              <tr key={file}>
                <td>
                  <code>{file}</code>
                </td>
                <td>{job}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </section>
      <section id="non-goals">
        <h2>Non-goals and known limits</h2>
        <ul>
          <li>
            No LoRA or fine-tuning on Jev. The policy is prompt rules plus a
            closed action space.
          </li>
          <li>
            No screenshots in the acting loop. Pixels would only be for an
            inspector or a recording.
          </li>
          <li>
            No shadow DOM, frames, canvas, uploads, pop-up tabs, nested
            scrolling, or arbitrary keyboard widgets, matching jev-ultrafast's
            MVP boundary. The sandbox iframe is the whole page here.
          </li>
          <li>
            The name algorithm covers labels, ARIA references and text, not the
            full accessible-name specification.
          </li>
          <li>
            The sandbox is synthetic, and one task is not a benchmark. A valid
            operation can still be the wrong one, and the run reports it rather
            than hiding it.
          </li>
        </ul>
      </section>
      <section id="try-it">
        <h2>Try it</h2>
        <ol>
          <li>
            Choose <strong>Run agent</strong>. The default goal is the one-way
            Zürich → London search. Watch the element table, the operation and
            target probabilities, and the cycle log.
          </li>
          <li>
            Leave the popover on to see the covered-target path: a click on the
            covered Search button is rejected, the rejection appears in recent
            history, and the policy has to dismiss it.
          </li>
          <li>
            Turn on slow results to see <code>WAIT</code> after Search, and use{" "}
            <strong>Verify now</strong> at any point to see what the verifier
            reads.
          </li>
          <li>
            Use <strong>One cycle</strong> to step,{" "}
            <strong>Observe only</strong> to read the table without a Jev call,
            and <strong>Export</strong> to download the whole trace.
          </li>
          <li>
            Set <code>TEXT_MODEL_API_KEY</code> on the server to generate text
            with a real small LLM through an OpenAI-compatible endpoint;
            otherwise Jev picks the value from spans of the goal.
          </li>
        </ol>
        <p>
          Reference implementation, measurements and the recorded Google Flights
          run:{" "}
          <a
            href="https://github.com/browser-use/jev-ultrafast"
            target="_blank"
            rel="noreferrer"
          >
            github.com/browser-use/jev-ultrafast <ArrowUpRight size={13} />
          </a>
          . Speculative fan-out is described in the{" "}
          <a
            href="https://docs.typesafe.ai/patterns/fan-out"
            target="_blank"
            rel="noreferrer"
          >
            TypeSafe docs <ArrowUpRight size={13} />
          </a>
          .
        </p>
      </section>
    </article>
  );
}
